### ISSUE TITLE
Unable to connect to Oracle SQL using python

### ISSUE THREAD

**Issue by murmeg01** [murmeg01/PyhtonIssues#1]
I'm using the following code on Spyder:
import cx_Oracle

def execute():
        user = 'regres_a'
        ip = '10.211.185.22'
        port = '1521'
        passwd = 'changeme12'
        sid = 'SITCR'
        connect_string = ("%s/%s@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=("
                          "COMMUNITY=TCP)(PROTOCOL=TCP)(Host=%s)(Port=%s)))("
                          "CONNECT_DATA=(SID=%s)(GLOBAL_NAME=%s)))") % (
            user, passwd, ip, port, sid, sid)
        print("Connecting with: %s" % connect_string)
        connection = cx_Oracle.connect(connect_string)
        cursor = connection.cursor()
        cursor.arraysize = 50
        cursor.execute("SELECT * from customer_node_history")
        row = cursor.fetchone()
        print(row[0])
        connection.close()          
execute()

Output:
runfile('C:/Users/murmeg01/Documents/001 MTNSA/AutomationTesting/Phython scripts/Into2Python/begin.py', wdir='C:/Users/murmeg01/Documents/001 MTNSA/AutomationTesting/Phython scripts/Into2Python')
Connecting with: regres_a/changeme12@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP)(PROTOCOL=TCP)(Host=10.211.185.22)(Port=1521)))(CONNECT_DATA=(SID=SITCR)(GLOBAL_NAME=SITCR)))
Traceback (most recent call last):

  File "<ipython-input-2-714562e5e8ff>", line 1, in <module>
    runfile('C:/Users/murmeg01/Documents/001 MTNSA/AutomationTesting/Phython scripts/Into2Python/begin.py', wdir='C:/Users/murmeg01/Documents/001 MTNSA/AutomationTesting/Phython scripts/Into2Python')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/murmeg01/Documents/001 MTNSA/AutomationTesting/Phython scripts/Into2Python/begin.py", line 71, in <module>
    execute()

  File "C:/Users/murmeg01/Documents/001 MTNSA/AutomationTesting/Phython scripts/Into2Python/begin.py", line 58, in execute
    connection = cx_Oracle.connect(connect_string)

DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "C:\Users\Devapps\product\11.2.0\client_1\BIN\oci.dll is not the correct architecture". See https://oracle.github.io/odpi/doc/installation.html#windows for help # #

**Comment by murmeg01** [comment]
Python Version:
C:\Users\murmeg01>python
Python 3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)] :: Anaconda custom (64-bit) on win32
Type "help", "copyright", "credits" or "license" for more information.

================================================================

OS Version:
64-bit

================================================================

Oracle Client version:
Client Shared Library 64-bit - 18.5.0.0.0
